---
version: "3.7"

services:
  app:
    build: .
    image: "emcasa/speedlify"
    hostname: local
    volumes:
      - ".:/app"
      - "app_node_modules:/app/node_modules"
    ports:
      - "9080:8080"
    command: yarn start

  nginx: 
    image: "nginx:1.20.2-alpine"
    volumes:
      - "./_site:/usr/share/nginx/html"
    ports:
      - "9090:80"

volumes:
  app_node_modules: {}
